<?php
/**
 * jFramework
 *
 * @version 2.3
 * @link https://github.com/ZionDevelopers/jframework/ The jFramework GitHub Project
 * @copyright 2010-2023, Júlio César de Oliveira
 * @author Júlio César de Oliveira <talk@juliocesar.me>
 * @license http://www.apache.org/licenses/LICENSE-2.0.html Apache 2.0 License
 */
?>
<?php echo $this->message;?>
<form action="" method="GET">
    <b>Security verification</b><br />
    <?php echo $this->captcha;?><br />
    <input type="text" name="captcha" maxlength="6" /><br />
    <input type="submit" value="Verify" />
</form> 