title: jFramework v2
description: An OOP MVC PHP 5.3+ Framework that run on PSR standards
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
github:
  zip_url: https://github.com/ZionDevelopers/jframework/archive/v2.2.zip
  tar_url: https://github.com/ZionDevelopers/jframework/archive/v2.2.tar.gz
