<?php
/**
 * jFramework
 *
 * @version 2.3
 * @link https://github.com/ZionDevelopers/jframework/ The jFramework GitHub Project
 * @copyright 2010-2023, Júlio César de Oliveira
 * @author Júlio César de Oliveira <talk@juliocesar.me>
 * @license http://www.apache.org/licenses/LICENSE-2.0.html Apache 2.0 License
 */

use \jFramework\Core\Tools;
?>
Let's Debug!
<iframe src="debug/pi" width="100%" height="500" border="0"></iframe>
<ul style="overflow: auto; width: 99%">
    	<li><b>Request</b>
		<?php Tools::debug($this->request); ?>
	</li>
	<li><b>Session Debug</b>
		<?php Tools::debug($_SESSION); ?>
	</li>
	<li><b>Database Cache</b>
		<?php Tools::debug($this->cache); ?>
	</li>
	<li><b>Server</b>
		<?php Tools::debug($_SERVER); ?>
	</li>
        <li><b>Get</b>
		<?php Tools::debug($this->get); ?>
	</li>
        <li><b>Post</b>
		<?php Tools::debug($this->post); ?>
	</li>
        <li><b>Data</b>
		<?php Tools::debug($this->data); ?>
	</li>
        <li><b>Cookies (Hum hm)</b>
		<?php Tools::debug($_COOKIE); ?>
	</li>	
</ul>