<?php
/**
 * jFramework
 *
 * @version 2.0.0
 * @link https://github.com/ZionDevelopers/jframework/ The jFramework GitHub Project
 * @copyright 2010-2014, Júlio César de Oliveira
 * @author Júlio César de Oliveira <talk@juliocesar.me>
 * @license http://www.apache.org/licenses/LICENSE-2.0.html Apache 2.0 License
 */
?>
<h1 id="pageTitle">Error 404</h1>
<h2><?php echo htmlentities($this->requestURL);?></h1>
<div><?php echo htmlentities($this->message);?></div>
